@startuml

autonumber

actor CampusManager as U
participant UI as UI
participant MD  as R

U -> UI : requests passage update
activate UI

UI -> R : patch('/api/passage/update')

activate R
|||
R -> R : updates passage, saves \n and returns it
|||
R -> UI : response status
UI -> U : operation success


@enduml