@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor FleetManager as U
participant UI as UI
participant MD  as R

U -> UI : request create robot
activate UI
UI -> R : post('/api/robot')

activate R
|||
R -> R : creates robot \n saves and returns it
|||
R -> UI : response status
deactivate R
|||
UI -> U : operation success
deactivate UI
@enduml