@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CampusManager as U
participant UI as UI
participant MD  as R

U -> UI : request list floor
activate UI
UI -> R : get('/api/floor')

activate R
|||
R -> R : finds all \n floors of building \n and returns them
|||
R -> UI : response status
deactivate R
|||
UI -> U : operation success
deactivate UI
@enduml