@startuml
hide circle
hide empty members

skinparam padding 1


skinparam interface {
    backgroundColor #0faaff
}

skinparam component {
    backgroundColor #0faaff
}

    interface CM_API_I as "**Campus management API**"
    interface TM_API_I as "**Task management API**"
    interface UM_API_I as "**User management API**"
    interface FM_API_I as "**Fleet management API**"

    interface CampusM_I as "**Campus Management UI**"
    interface TaskM_I as "**Task Management UI**"
    interface UserM_I as "**User Management UI**"
    interface FleetM_I as "**Fleet Management UI**"

component [RobDroneGo_I] <<component>><<system(C4)>> as "RobDroneGo"{
    portout " " as p1_I #0faaff
    port " " as p2_I #0faaff
    port " " as p3_I #0faaff
    port " " as p4_I #0faaff
    port " " as p5_I #0faaff
    port " " as p6_I #0faaff
    port " " as p7_I #0faaff
    port " " as p8_I #0faaff
    port " " as p9_I #0faaff


    interface Planning_API_I as "**Planning API**"
    interface MD_API_I as "**MD API**"

    component [MD_I] <<component>><<container(C4)>> as "Master Data (MD)"{
        port " " as pMD1_I #0faaff
        port " " as pMD2_I #0faaff
        portout " " as pMD3_I #0faaff
        port " " as pMD4_I #0faaff
        port " " as pMD5_I #0faaff
        port " " as pMD6_I #0faaff
        port " " as pMD7_I #0faaff

    }

    component [FE_I] <<component>><<container(C4)>> as "FrontEnd"{
        portout " " as pFE5_I #0faaff
        portin " " as pFE2_I #0faaff
        portin " " as pFE1_I #0faaff
        portin " " as pFE3_I #0faaff
        portin " " as pFE4_I #0faaff
    }



    component [Planning_I] <<component>><<system(C4)>> as "Planning"{
        portout " " as pp1_I #0faaff
    }

}

interface filesystem_API as "**filesystem API**"

p1_I -u-( filesystem_API
p2_I -u- CampusM_I
p3_I -u- FleetM_I
p4_I -u- CM_API_I
p5_I -u- FM_API_I
p6_I -u- TM_API_I
p7_I -u- UM_API_I
p8_I -u- TaskM_I
p9_I -u- UserM_I

pFE1_I -u- p2_I
pFE2_I -u- p3_I
pFE3_I -u- p8_I
pFE4_I -u- p9_I
pFE5_I -d-( MD_API_I

pMD1_I -u-- p4_I
pMD2_I -u-- p5_I
pMD3_I -u-- p1_I
pMD4_I -u- MD_API_I
pMD5_I -u--( Planning_API_I
pMD6_I -u-- p7_I
pMD7_I -u-- p6_I

pp1_I -- Planning_API_I

skinparam node{
    backgroundColor #lightblue
}

skinparam componentFontStyle<<component>> bold

node "localhost:??" as Host_F {
  component "Browser" <<component>> as B{
    component UI <<component>> as "UI"
  }
}

node Remote_F as "Remote Server" {
    component CM <<component>> as "Campus Management"
    component FM <<component>> as "Fleet Management"
    component Planning <<component>> as "Planning"
    component TM <<component>> as "Task Management"
    component UM <<component>> as "User Management"
}


Host_F -d- Remote_F: http/s

[FE_I] -u.--- UI : manifest

[MD_I] -u.--- CM : manifest
[MD_I] -u.--- TM : manifest
[MD_I] -u.--- FM : manifest
[MD_I] -u.--- UM : manifest
[Planning_I] -u.--- Planning : manifest

[RobDroneGo_I] -d[hidden]--------- [RobDroneGo_L] : manifest


@enduml