@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant UI as UI
participant Route  as R
participant Controller as C
participant CreatingDTO as CDTO
participant Mapper as M
participant DTO as DTO
participant Service as S
participant Domain as D
participant Repository as Repo


activate UI

UI -> R : patch('/api/pisos/update')

activate R

R -> C : patch

activate C

C -> CDTO : recives body info

activate CDTO

CDTO -> M : ToDTO

activate M

M -> DTO : new DTO

activate DTO

DTO -> M : return DTO

deactivate DTO

M -> CDTO : return DTO

deactivate M

CDTO -> C : return DTO

deactivate CDTO

C -> S : chamada do serviço de piso

activate S

S -> Repo : get piso

activate Repo

Repo -> M : toDomain

activate M

M -> D : cria objecto de dominio

activate D

D -> M : return objecto

deactivate D

M -> Repo : return objecto

deactivate M

Repo -> S : return objecto

deactivate Repo

S -> D : update informação

activate D
deactivate D

S-> Repo : update piso

activate Repo

Repo -> M : toDTO

activate M
deactivate M

Repo -> S : return DTO

deactivate Repo

S-> C : return dto

deactivate S

C -> R : status 201

deactivate C

R -> UI : success message

@enduml