@startuml

hide circle
hide empty members

skinparam padding 1


skinparam interface {
    backgroundColor #0faaff
}

skinparam component {
    backgroundColor #0faaff
}

interface UI_Campus as "**UI Campus**"
interface UI_Fleet as "**UI Fleet**"
interface API_Fleet as "**API Fleet**"
interface API_Campus as "**API Campus**"

component UI_L <<component>> <<C4 container>> as "**Frontend (UI)**" {
port p1 as " " #0faaff
port p2 as " " #0faaff
port p3 as " " #0faaff
port p4 as " " #0faaff

        component View <<component>> as "**View**"{
            port p5 as " " #0faaff
            port p6 as " " #0faaff
        }
        component HTTPDriver <<component>> as "**HTTP Driver**"{
           port p7 as " " #0faaff
           port p8 as " " #0faaff
        }
        component ViewModel <<component>> as "**View Model**"
        component Controller <<component>> as "**Controller**"
        component Service <<component>> as "**Service**"
        component Model <<component>> as "**Model**"
        component Repository <<component>> as "**Repo/Adapter**"
        component DTO <<component>> as "**DTO Exterior-Interior**"
        component DTO1 <<component>> as "**DTO Service-Controller**"

        interface C_API as "**Controller** \n **API**"
        interface VM_API as "**View Model** \n **API**"
        interface Ob_API as "**Observer** \n **API**"
        interface S_API as "**Service** \n **API**"
        interface R_API as "**Repo** \n **API**"
        interface HTTP_API as "**HTTP Driver** \n **API**"
        interface DTO_API as "**DTO** \n **API**"
        interface Model_API as "**Model** \n **API**"
        interface DTO2_API as "**DTO2** \n **API**"

UI_Campus -d- p1
UI_Fleet -d- p2
p1 -- p5
p2 -- p6
"View" -right- Ob_API
Ob_API )-- "ViewModel"
"View" -down-( C_API
"View" -down-( VM_API
C_API -down- Controller
VM_API -down- Controller
VM_API )-- ViewModel
Controller -down-( S_API
Controller -down-( DTO2_API
S_API -down- Service
DTO2_API -down- Service
DTO2_API )-down- DTO1




API_Fleet )-down- p3
API_Campus )-down- p4
p3 -- p7
p4 -- p8
HTTPDriver -down- HTTP_API
HTTP_API )-down- "Repository"
HTTPDriver -down-( DTO_API
DTO_API -right- DTO
"Repository" -left- R_API
R_API )-left-"Service"
"Repository" ..> "Service"
Service -down-( Model_API
Model -down- Model_API
Model_API )-down- "Repository"


}

    interface Cam_UI_I as "**UI Campus**"
    interface F_UI_I as "**UI Fleet**"
    interface Cam_API_I as "**Campus API**"
    interface F_API_I as "**Fleet API**"

component UI_I <<component>><<container(C4)>>as "Frontend (UI)"{

    port " " as p1_I
    port " " as p2_I
    port " " as p3_I
    port " " as p4_I


    folder Angular_I as "Angular Component"{
        component HTML_I <<component>> as "**HTML + CSS + JS**"{
            port " " as pH1_I
            port " " as pH2_I

            pH1_I - p1_I
            pH2_I - p2_I
        }
        component Component_I <<component>> as "**Component**"
        interface C_API_I as "**Component API**"

        HTML_I -down-( C_API_I
        Component_I -up- C_API_I
    }

    interface Observer_I as "**Observer API**"
    component Service_I <<component>> as "**Service**"
    interface S_API_I as "**Service API**"
    component Model_I <<component>> as "**Model**"
    interface M_API_I as "**Model API**"
    component Driver_I <<component>> as "**HTTP Driver**"{
        port " " as pD1_I
        port " " as pD2_I

        pD1_I -u- p3_I
        pD2_I -u- p4_I
    }
    interface D_API_I as "**HTTP Driver API**"

    Service_I -r- S_API_I
    Model_I -- M_API_I
    Driver_I -r- D_API_I

    Component_I -r-( Observer_I
    Model_I -l-- Observer_I

    Component_I -down----( S_API_I
    Component_I --( M_API_I

    Service_I -r-( D_API_I
    Service_I --( M_API_I

    Driver_I --( M_API_I

    p1_I -up- Cam_UI_I
    p2_I -up- F_UI_I
    p3_I -up-( Cam_API_I
    p4_I -up-( F_API_I


    Service_I -[hidden]up--- Component_I
    Model_I -[hidden]up--- Driver_I
    HTML_I -[hidden]right--- Component_I
    Driver_I -[hidden]d--- Angular_I
}

View -u------.> HTML_I : manifest
Controller -u-------.> Component_I : manifest
HTTPDriver -u-------.> Driver_I : manifest
Service -u----.> Service_I : manifest
Model -u---.> Model_I : manifest

UI_L -l[hidden]----- UI_I
UI_I -r[hidden]----- UI_L
@enduml