@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CampusManager as U
participant UI as UI
participant MD  as R

U -> UI : request update building
activate UI
UI -> R : patch('/api/building')

activate R
|||
R -> R : edits building, saves and returns it.
|||
R -> UI : response status
deactivate R
|||
UI -> U : operation success
deactivate UI

@enduml